var grids = [
    // colors
    [
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Black",
        "White",
        "Orange",
        "Pink",
        "Brown",
        "Purple",
        "Gray",
        "Gold",
        "Silver",
        "Bronze",
        "Rainbow",
        "Cream",
        "Turquoise",
        "Lilac"
    ],
    // food
    [
        "Curry",
        "Chips",
        "Salad",
        "Fish",
        "Chicken",
        "Sausage",
        "Orange",
        "Mango",
        "Leek",
        "Tomato",
        "Pepper",
        "Chilli",
        "Beef",
        "Pizza",
        "Pasta",
        "Ice cream",
        "Chocolate",
        "Strawberries"
    ],
    // capitals
    [
        "London",
        "Moscow",
        "Paris",
        "Berlin",
        "Madrid",
        "Rome",
        "Cairo",
        "Helsinki",
        "Stockholm",
        "Oslo",
        "Washington",
        "Mexico city",
        "Bejing",
        "Tokyo",
        "Seoul",
        "Vienna",
        "Nairobi",
        "Marrakesh"
    ],
    // rooms
    [
        "Hallway",
        "Kitchen",
        "Dining room",
        "Sitting room",
        "Bathroom",
        "Bedroom",
        "Cellar",
        "Attic",
        "Dungeon",
        "Conservatory",
        "Shed",
        "Study",
        "Garage",
        "Music room",
        "Workshop",
        "Greenhouse",
        "Gym",
        "Studio"
    ],
    // pets
    [
        "Dog",
        "Cat",
        "Parrot",
        "Rabbit",
        "Hamster",
        "Guinea pig",
        "Goldfish",
        "Snake",
        "Lizard",
        "Horse",
        "Alpaca",
        "Frog",
        "Rat",
        "Crab",
        "Budgie",
        "Spider",
        "Donkey",
        "Owl"
    ],
    // harry potter
    [
        "Harry Potter",
        "Ron Weasley",
        "Hermione Granger",
        "Neville Longbottom",
        "Luna Lovegood",
        "Albus Dumbledore",
        "Minerva Mcgonnagal",
        "Pomona Sprout",
        "Severus Snape",
        "Filius Flitwick",
        "Sirius Black",
        "Remus Lupin",
        "Peter Pettigrew",
        "Lord Voldemort",
        "Draco Malfoy",
        "Rubeus Hagrid",
        "Dobby",
        "Argus Filch"
    ],
    // marvel heros
    [
        "Spiderman",
        "Ironman",
        "Hulk",
        "Captain America",
        "Thor",
        "Deadpool",
        "Wolverine",
        "Groot",
        "Loki",
        "Star-lord",
        "Gamora",
        "Drax",
        "Magneto",
        "Jessica Jones",
        "Daredevil",
        "Charles Xavier",
        "Ant man",
        "Luke Cage"
    ],
    // disney
    [
        "Cinderella",
        "Belle",
        "Snow White",
        "Ariel",
        "Mulan",
        "Jasmine",
        "Pocahontas",
        "Mickey Mouse",
        "Donald Duck",
        "Pluto",
        "Bambi",
        "Peter Pan",
        "Captain Hook",
        "Baloo",
        "Winnie the Pooh",
        "Aladdin",
        "Hercules",
        "Tarzan"
    ],
    // sea cratures
    [
        "Starfish",
        "Shark",
        "Whale",
        "Dolphin",
        "Cod",
        "Jellyfish",
        "Seahorse",
        "Puffer fish",
        "Orka",
        "Coral",
        "Oysters",
        "Mussels",
        "Octopus",
        "Kraken",
        "Turtle",
        "Seal",
        "Sea cucumber",
        "Sting ray"
    ],
    // sports
    [
        "Football",
        "Rugby",
        "Athletics",
        "Swimming",
        "Hockey",
        "Tennis",
        "Badminton",
        "Golf",
        "Squash",
        "Gymnastics",
        "Trampolining",
        "Cycling",
        "Volleyball",
        "Cricket",
        "Baseball",
        "Basketball",
        "Skiing",
        "Sailing"
    ],
    // hobbies
    [
        "Stamps",
        "Trains",
        "Model Making",
        "Knitting",
        "Fishing",
        "Reading",
        "Painting",
        "Gardening",
        "Sailing",
        "Travel",
        "Walking",
        "Pottery",
        "Cooking",
        "Yoga",
        "Photography",
        "Hiking",
        "Bird watching",
        "Singing"
    ],
    // school
    [
        "Maths",
        "Chemistry",
        "Physics",
        "Biology",
        "History",
        "Philosophy",
        "Geography",
        "English",
        "Economics",
        "French",
        "Art",
        "Music",
        "Physical education",
        "Latin",
        "Religious studies",
        "Technology",
        "Geology",
        "Drama"
    ],
    // transport
    [
        "Plane",
        "Car",
        "Tank",
        "Helicopter",
        "Cruise ship",
        "Hovercraft",
        "Motorbike",
        "Bus",
        "Segway",
        "Cable car",
        "Jet ski",
        "Hot air balloon",
        "Train",
        "Spaceship",
        "Magic carpet",
        "Broomstick",
        "Cycle",
        "Skateboard"
    ],
    // jobs
    [
        "Fisherman",
        "Lumberjack",
        "Nurse",
        "Waiter",
        "Lighthouse keeper",
        "Secretary",
        "Accountant",
        "Teacher",
        "Lorry driver",
        "Security guard",
        "Chef",
        "Architect",
        "Police officer",
        "Lawyer",
        "Carpenter",
        "Butcher",
        "Doctor",
        "Film director"
    ],
    // civilizations
    [
        'Romans',
        'Egyptians',
        'Mayans',
        'Mongols',
        'Aztecs',
        'Japanese',
        'Persians',
        'Greeks',
        'Turks',
        'Vikings',
        'Incas',
        'Spanish',
        'Zulu',
        'Chinese',
        'Spartans',
        'Aliens',
        'Eskimos',
        'Samurai'
    ],
    // tattoos
    [
        'Stars',
        'Angel',
        'Wings',
        'Dragon',
        'Eagle',
        'Fairy',
        'Heart',
        'Skull',
        'Sword',
        'Tiger',
        'Swallows',
        'Flower',
        'Butterfly',
        'Cross',
        'Owl',
        'Anchor',
        'Whale',
        'Lightning'
    ],
    // Geography
    [
        'Lake',
        'Sea',
        'Valley',
        'Mountain',
        'River',
        'Desert',
        'Ocean',
        'Forest',
        'Jungle',
        'Island',
        'Glacier',
        'Waterfall',
        'Volcano',
        'Cave',
        'Arctic',
        'Swamp',
        'Gorge',
        'Reef'
    ]
];

module.exports = grids;